#Spring
spring:
  ## DataSource
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
      url: jdbc:oracle:thin:@192.168.8.172:1521:orcl
      username: sb
      password: sb
      driver-class-name: oracle.jdbc.OracleDriver
      # 数据源配置，初始化大小、最小、最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 连接等待超时时间
      maxWait: 60000
      # 配置隔多久进行一次检测（检测可以关闭的空闲连接）
      timeBetweenEvictionRunsMillis: 3000
      # 配置连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'ZTM' FROM DUAL
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且制定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，‘wall’用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能：慢SQL记录
      connectionProperties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  ## session
  session:
    store-type: redis
  ## Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms
    lettuce:
      pool:
        min-idle: 0
    database: 0
  application:
    name: myspringboot
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  ## thymeleaf
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
  ## http
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
# server config
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 8080
  servlet:
    context-path: /swglpt
    session:
      timeout: PT1M
# mybatis
mybatis:
  type-aliases-package: com.esen.swglpt.mapper
  mapper-locations: classpath:com/esen/swglpt/mapper/*.xml
# logging
logging:
  level:
    com.esen.swglpt.mapper: debug